### ISSUE TITLE
Kaj je `.recommenders`?

### ISSUE THREAD

**Issue by andrejbauer** [metodj/hex#1]
To verjetno ne spada v repo, še posebej zato, ker se omenja nekakšen "cache". Preverita.

**Comment by metodj** [comment]
.recommenders datoteka dodana v git ignore. Commit f476409.

**Comment by andrejbauer** [comment]
Ampak čisto iz fribca, a vesta, od kod se je vzela ta folder? A je to Eclipse naredil?

**Comment by janrems** [comment]
Če sem prav razumel gre za 'code completion', ki olajša delo na različnih API-jih in jih generira Eclipse. So pa za osnovno urejanje kode na več napravah bojda nepotrebni.
