### ISSUE TITLE
Enum se našteva z VELIKIMI

### ISSUE THREAD

**Issue by andrejbauer** [metodj/hex#2]
V razredu `Igralec` (in verjetno tudi ostalih, ki so `enum`) bi morali biti možni elementi našteti `Z_VELIKIMI_CRKAMI`.

**Comment by andrejbauer** [comment]
Ta issue je narobe zaprt! Nujno je treba navesti commit, v katerem je bil zaprt!

**Comment by metodj** [comment]
Za napačno zapiranje se opravičujem. 
Issue je bil upoštevan in popravljen s commit-om 07e8dc9.
Šlo je za velik commit, saj sva danes velik del kode izbrisala in zastavila na novo.

**Comment by andrejbauer** [comment]
Upam, da sta se dala na poseben branch, preden sta šla vse pobrisat?

**Comment by metodj** [comment]
Nisva, shranila sva si staro kodo na računalniku. 
Kako pravilno delati s sistemom branch-ov še ne veva, si bova pogledala za naslednjič.

**Comment by andrejbauer** [comment]
Tole se zdi v redu: https://learngitbranching.js.org (izbereš "branching in git").

Sicer pa, če začneš delati nekaj, kar je velika sprememba, najprej narediš branch, potem delaš s tem branchom, dokler nisi zadovoljen, potem pa narediš merge nazaj na `master`. Prednost je v tem, da imaš lahko več branchov in da `master` in "zapackan" z nedelujočo kodo.
