### ISSUE TITLE
Strategija za igranje igre

### ISSUE THREAD

**Issue by andrejbauer** [metodj/hex#3]
Lahko malo [pobrskata po internetu](http://www.cs.cornell.edu/~adith/docs/y_hex.pdf) in pogledata, kaj so počeli ostali ljudje, da so naprogramirali hevrsitike. Lahko poskusita, kako bi delovalo ocenjevanje s pomočjo prerezov grafa (glejta npr. izreke [max-flow min-cut](https://en.wikipedia.org/wiki/Max-flow_min-cut_theorem) in algoritme v zvezi s tem).

**Comment by metodj** [comment]
Upoštevan nasvet. Ford Fulkerson algoritem se je precej dobro obnesel. Commit: 201cdda9c9c9f6d1996ade9489fe34033a795bf2
