### ISSUE TITLE
Alpha-beta pruning

### ISSUE THREAD

**Issue by janrems** [metodj/hex#7]
@andrejbauer
Prvo kot prvo bi vas obvestil, da sva s kolegom uspela odpraviti bug glede lihih globin v minmaxu o katerem smo govorili popoldne. Nato pa sva pri poizkusu implementacije algoritma alpha-beta pruning naletela na težave, računalnik namreč postane čisto  neinteligenten. Pred implementacijo sva naredila nov branch alphaBeta kjer sva spremenila in preimenovala minmax v alphaBeta. Prejšnja verzija minmax algoritma, ki je delovala je na branchu master. Imate morda kakšno idejo, kje bi lahko bila težava? Problem ne bi smel biti v shranjevanju potez v seznam in naključnemu žrebanju le-teh, saj sva algoritem poizkusila impementirati tudi z eno samo "najboljšo" potezo.

**Comment by metodj** [comment]
Bug odpravljen s commitom f470403. Zahvala gre Žanu Šifrerju @stifler9  , ki naju je opozoril na bug.

Je pa sedaj postalo očitno, da računalnik igra slabše kot pri prvi implementaciji ford fulkerson algoritma. Nekje med mergom branchev in popravljanjem razreda Ocena.java sva zgleda povozila pravilno delovanje hevrisitik.  Potrebno bo iti nazaj do commita 201cdda9c9c9f6d1996ade9489fe34033a795bf2 in začeti z delom na igri računalnika od te točke naprej.
